//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Administracion.ServicioWCF {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServicio", Namespace="http://tempuri.org/")]
    public partial class Servicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AltaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambioPassOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaPagoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicio() {
            this.Url = global::Administracion.Properties.Settings.Default.Administracion_ServicioWCF_Servicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AltaUsuarioCompletedEventHandler AltaUsuarioCompleted;
        
        /// <remarks/>
        public event BajaUsuarioCompletedEventHandler BajaUsuarioCompleted;
        
        /// <remarks/>
        public event ModificarUsuarioCompletedEventHandler ModificarUsuarioCompleted;
        
        /// <remarks/>
        public event BuscarUsuarioCompletedEventHandler BuscarUsuarioCompleted;
        
        /// <remarks/>
        public event CambioPassCompletedEventHandler CambioPassCompleted;
        
        /// <remarks/>
        public event LogueoCompletedEventHandler LogueoCompleted;
        
        /// <remarks/>
        public event AltaPagoCompletedEventHandler AltaPagoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/AltaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario unUsuario) {
            this.Invoke("AltaUsuario", new object[] {
                        unUsuario});
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(Usuario unUsuario) {
            this.AltaUsuarioAsync(unUsuario, null);
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(Usuario unUsuario, object userState) {
            if ((this.AltaUsuarioOperationCompleted == null)) {
                this.AltaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaUsuarioOperationCompleted);
            }
            this.InvokeAsync("AltaUsuario", new object[] {
                        unUsuario}, this.AltaUsuarioOperationCompleted, userState);
        }
        
        private void OnAltaUsuarioOperationCompleted(object arg) {
            if ((this.AltaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/BajaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario unUsuario) {
            this.Invoke("BajaUsuario", new object[] {
                        unUsuario});
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(Usuario unUsuario) {
            this.BajaUsuarioAsync(unUsuario, null);
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(Usuario unUsuario, object userState) {
            if ((this.BajaUsuarioOperationCompleted == null)) {
                this.BajaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaUsuarioOperationCompleted);
            }
            this.InvokeAsync("BajaUsuario", new object[] {
                        unUsuario}, this.BajaUsuarioOperationCompleted, userState);
        }
        
        private void OnBajaUsuarioOperationCompleted(object arg) {
            if ((this.BajaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/ModificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario unUsuario) {
            this.Invoke("ModificarUsuario", new object[] {
                        unUsuario});
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(Usuario unUsuario) {
            this.ModificarUsuarioAsync(unUsuario, null);
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(Usuario unUsuario, object userState) {
            if ((this.ModificarUsuarioOperationCompleted == null)) {
                this.ModificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModificarUsuario", new object[] {
                        unUsuario}, this.ModificarUsuarioOperationCompleted, userState);
        }
        
        private void OnModificarUsuarioOperationCompleted(object arg) {
            if ((this.ModificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/BuscarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario BuscarUsuario(int pCedula, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pCedulaSpecified) {
            object[] results = this.Invoke("BuscarUsuario", new object[] {
                        pCedula,
                        pCedulaSpecified});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(int pCedula, bool pCedulaSpecified) {
            this.BuscarUsuarioAsync(pCedula, pCedulaSpecified, null);
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(int pCedula, bool pCedulaSpecified, object userState) {
            if ((this.BuscarUsuarioOperationCompleted == null)) {
                this.BuscarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuarioOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuario", new object[] {
                        pCedula,
                        pCedulaSpecified}, this.BuscarUsuarioOperationCompleted, userState);
        }
        
        private void OnBuscarUsuarioOperationCompleted(object arg) {
            if ((this.BuscarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuarioCompleted(this, new BuscarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/CambioPass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CambioPass([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario unUsuario) {
            this.Invoke("CambioPass", new object[] {
                        unUsuario});
        }
        
        /// <remarks/>
        public void CambioPassAsync(Usuario unUsuario) {
            this.CambioPassAsync(unUsuario, null);
        }
        
        /// <remarks/>
        public void CambioPassAsync(Usuario unUsuario, object userState) {
            if ((this.CambioPassOperationCompleted == null)) {
                this.CambioPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambioPassOperationCompleted);
            }
            this.InvokeAsync("CambioPass", new object[] {
                        unUsuario}, this.CambioPassOperationCompleted, userState);
        }
        
        private void OnCambioPassOperationCompleted(object arg) {
            if ((this.CambioPassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambioPassCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/Logueo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario Logueo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pNomUsu) {
            object[] results = this.Invoke("Logueo", new object[] {
                        pNomUsu});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoAsync(string pNomUsu) {
            this.LogueoAsync(pNomUsu, null);
        }
        
        /// <remarks/>
        public void LogueoAsync(string pNomUsu, object userState) {
            if ((this.LogueoOperationCompleted == null)) {
                this.LogueoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoOperationCompleted);
            }
            this.InvokeAsync("Logueo", new object[] {
                        pNomUsu}, this.LogueoOperationCompleted, userState);
        }
        
        private void OnLogueoOperationCompleted(object arg) {
            if ((this.LogueoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoCompleted(this, new LogueoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicio/AltaPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaPago([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Pago unPago) {
            this.Invoke("AltaPago", new object[] {
                        unPago});
        }
        
        /// <remarks/>
        public void AltaPagoAsync(Pago unPago) {
            this.AltaPagoAsync(unPago, null);
        }
        
        /// <remarks/>
        public void AltaPagoAsync(Pago unPago, object userState) {
            if ((this.AltaPagoOperationCompleted == null)) {
                this.AltaPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaPagoOperationCompleted);
            }
            this.InvokeAsync("AltaPago", new object[] {
                        unPago}, this.AltaPagoOperationCompleted, userState);
        }
        
        private void OnAltaPagoOperationCompleted(object arg) {
            if ((this.AltaPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaPagoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cajero))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gerente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class Usuario {
        
        private int cedulaField;
        
        private bool cedulaFieldSpecified;
        
        private string nomCompletoField;
        
        private string nomUsuField;
        
        private string passField;
        
        /// <remarks/>
        public int Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CedulaSpecified {
            get {
                return this.cedulaFieldSpecified;
            }
            set {
                this.cedulaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomCompleto {
            get {
                return this.nomCompletoField;
            }
            set {
                this.nomCompletoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomUsu {
            get {
                return this.nomUsuField;
            }
            set {
                this.nomUsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class Empresa {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string dirFiscalField;
        
        private int rutField;
        
        private bool rutFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DirFiscal {
            get {
                return this.dirFiscalField;
            }
            set {
                this.dirFiscalField = value;
            }
        }
        
        /// <remarks/>
        public int Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RutSpecified {
            get {
                return this.rutFieldSpecified;
            }
            set {
                this.rutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class TipoContrato {
        
        private int codContratoField;
        
        private bool codContratoFieldSpecified;
        
        private string nombreField;
        
        private Empresa unaEmpField;
        
        /// <remarks/>
        public int CodContrato {
            get {
                return this.codContratoField;
            }
            set {
                this.codContratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodContratoSpecified {
            get {
                return this.codContratoFieldSpecified;
            }
            set {
                this.codContratoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Empresa UnaEmp {
            get {
                return this.unaEmpField;
            }
            set {
                this.unaEmpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class Factura {
        
        private int codCliField;
        
        private bool codCliFieldSpecified;
        
        private System.DateTime fechaVtoField;
        
        private bool fechaVtoFieldSpecified;
        
        private int montoField;
        
        private bool montoFieldSpecified;
        
        private TipoContrato unTipoContratoField;
        
        /// <remarks/>
        public int CodCli {
            get {
                return this.codCliField;
            }
            set {
                this.codCliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCliSpecified {
            get {
                return this.codCliFieldSpecified;
            }
            set {
                this.codCliFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaVto {
            get {
                return this.fechaVtoField;
            }
            set {
                this.fechaVtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaVtoSpecified {
            get {
                return this.fechaVtoFieldSpecified;
            }
            set {
                this.fechaVtoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoContrato UnTipoContrato {
            get {
                return this.unTipoContratoField;
            }
            set {
                this.unTipoContratoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class Pago {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private Factura[] lasFacturasField;
        
        private int montoTotalField;
        
        private bool montoTotalFieldSpecified;
        
        private int numeroIntField;
        
        private bool numeroIntFieldSpecified;
        
        private Cajero usuCajeroField;
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Factura[] LasFacturas {
            get {
                return this.lasFacturasField;
            }
            set {
                this.lasFacturasField = value;
            }
        }
        
        /// <remarks/>
        public int MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoTotalSpecified {
            get {
                return this.montoTotalFieldSpecified;
            }
            set {
                this.montoTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NumeroInt {
            get {
                return this.numeroIntField;
            }
            set {
                this.numeroIntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroIntSpecified {
            get {
                return this.numeroIntFieldSpecified;
            }
            set {
                this.numeroIntFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cajero UsuCajero {
            get {
                return this.usuCajeroField;
            }
            set {
                this.usuCajeroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class Cajero : Usuario {
        
        private System.DateTime horanFinField;
        
        private bool horanFinFieldSpecified;
        
        private System.DateTime horanIniField;
        
        private bool horanIniFieldSpecified;
        
        /// <remarks/>
        public System.DateTime HoranFin {
            get {
                return this.horanFinField;
            }
            set {
                this.horanFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoranFinSpecified {
            get {
                return this.horanFinFieldSpecified;
            }
            set {
                this.horanFinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime HoranIni {
            get {
                return this.horanIniField;
            }
            set {
                this.horanIniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoranIniSpecified {
            get {
                return this.horanIniFieldSpecified;
            }
            set {
                this.horanIniFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    public partial class Gerente : Usuario {
        
        private string correoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AltaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BajaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ModificarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarUsuarioCompletedEventHandler(object sender, BuscarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CambioPassCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void LogueoCompletedEventHandler(object sender, LogueoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AltaPagoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591