//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.ServicioWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Administracion.ServicioWCF.Gerente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Administracion.ServicioWCF.Cajero))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCompleto {
            get {
                return this.NomCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCompletoField, value) != true)) {
                    this.NomCompletoField = value;
                    this.RaisePropertyChanged("NomCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUsu {
            get {
                return this.NomUsuField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsuField, value) != true)) {
                    this.NomUsuField = value;
                    this.RaisePropertyChanged("NomUsu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gerente", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Gerente : Administracion.ServicioWCF.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cajero", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Cajero : Administracion.ServicioWCF.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoranFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoranIniField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HoranFin {
            get {
                return this.HoranFinField;
            }
            set {
                if ((this.HoranFinField.Equals(value) != true)) {
                    this.HoranFinField = value;
                    this.RaisePropertyChanged("HoranFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HoranIni {
            get {
                return this.HoranIniField;
            }
            set {
                if ((this.HoranIniField.Equals(value) != true)) {
                    this.HoranIniField = value;
                    this.RaisePropertyChanged("HoranIni");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioWCF.Factura[] LasFacturasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MontoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioWCF.Cajero UsuCajeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioWCF.Factura[] LasFacturas {
            get {
                return this.LasFacturasField;
            }
            set {
                if ((object.ReferenceEquals(this.LasFacturasField, value) != true)) {
                    this.LasFacturasField = value;
                    this.RaisePropertyChanged("LasFacturas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MontoTotal {
            get {
                return this.MontoTotalField;
            }
            set {
                if ((this.MontoTotalField.Equals(value) != true)) {
                    this.MontoTotalField = value;
                    this.RaisePropertyChanged("MontoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroInt {
            get {
                return this.NumeroIntField;
            }
            set {
                if ((this.NumeroIntField.Equals(value) != true)) {
                    this.NumeroIntField = value;
                    this.RaisePropertyChanged("NumeroInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioWCF.Cajero UsuCajero {
            get {
                return this.UsuCajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuCajeroField, value) != true)) {
                    this.UsuCajeroField = value;
                    this.RaisePropertyChanged("UsuCajero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodCliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioWCF.TipoContrato UnTipoContratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCli {
            get {
                return this.CodCliField;
            }
            set {
                if ((this.CodCliField.Equals(value) != true)) {
                    this.CodCliField = value;
                    this.RaisePropertyChanged("CodCli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVto {
            get {
                return this.FechaVtoField;
            }
            set {
                if ((this.FechaVtoField.Equals(value) != true)) {
                    this.FechaVtoField = value;
                    this.RaisePropertyChanged("FechaVto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioWCF.TipoContrato UnTipoContrato {
            get {
                return this.UnTipoContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnTipoContratoField, value) != true)) {
                    this.UnTipoContratoField = value;
                    this.RaisePropertyChanged("UnTipoContrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoContrato", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class TipoContrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.ServicioWCF.Empresa UnaEmpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodContrato {
            get {
                return this.CodContratoField;
            }
            set {
                if ((this.CodContratoField.Equals(value) != true)) {
                    this.CodContratoField = value;
                    this.RaisePropertyChanged("CodContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.ServicioWCF.Empresa UnaEmp {
            get {
                return this.UnaEmpField;
            }
            set {
                if ((object.ReferenceEquals(this.UnaEmpField, value) != true)) {
                    this.UnaEmpField = value;
                    this.RaisePropertyChanged("UnaEmp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirFiscal {
            get {
                return this.DirFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.DirFiscalField, value) != true)) {
                    this.DirFiscalField = value;
                    this.RaisePropertyChanged("DirFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rut {
            get {
                return this.RutField;
            }
            set {
                if ((this.RutField.Equals(value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWCF.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaUsuario", ReplyAction="http://tempuri.org/IServicio/AltaUsuarioResponse")]
        void AltaUsuario(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaUsuario", ReplyAction="http://tempuri.org/IServicio/BajaUsuarioResponse")]
        void BajaUsuario(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarUsuario", ReplyAction="http://tempuri.org/IServicio/ModificarUsuarioResponse")]
        void ModificarUsuario(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarUsuario", ReplyAction="http://tempuri.org/IServicio/BuscarUsuarioResponse")]
        Administracion.ServicioWCF.Usuario BuscarUsuario(int pCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CambioPass", ReplyAction="http://tempuri.org/IServicio/CambioPassResponse")]
        void CambioPass(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Logueo", ReplyAction="http://tempuri.org/IServicio/LogueoResponse")]
        Administracion.ServicioWCF.Usuario Logueo(string pNomUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregaExtras", ReplyAction="http://tempuri.org/IServicio/AgregaExtrasResponse")]
        void AgregaExtras(int pCedula, System.DateTime pFecha, int pMinutos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaPago", ReplyAction="http://tempuri.org/IServicio/AltaPagoResponse")]
        void AltaPago(Administracion.ServicioWCF.Pago unPago, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PagoDeUnaFactura", ReplyAction="http://tempuri.org/IServicio/PagoDeUnaFacturaResponse")]
        System.DateTime PagoDeUnaFactura(int codContrato, int codEmp, int monto, int codCli, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/listar", ReplyAction="http://tempuri.org/IServicio/listarResponse")]
        Administracion.ServicioWCF.Pago[] listar(Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarEmpresa", ReplyAction="http://tempuri.org/IServicio/BuscarEmpresaResponse")]
        Administracion.ServicioWCF.Empresa BuscarEmpresa(int codEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaEmpresa", ReplyAction="http://tempuri.org/IServicio/AltaEmpresaResponse")]
        void AltaEmpresa(Administracion.ServicioWCF.Empresa unaEmpresa, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaEmpresa", ReplyAction="http://tempuri.org/IServicio/BajaEmpresaResponse")]
        void BajaEmpresa(Administracion.ServicioWCF.Empresa unaEmpresa, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarEmpresa", ReplyAction="http://tempuri.org/IServicio/ModificarEmpresaResponse")]
        void ModificarEmpresa(Administracion.ServicioWCF.Empresa unaEmpresa, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresas", ReplyAction="http://tempuri.org/IServicio/ListarEmpresasResponse")]
        Administracion.ServicioWCF.Empresa[] ListarEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarContrato", ReplyAction="http://tempuri.org/IServicio/BuscarContratoResponse")]
        Administracion.ServicioWCF.TipoContrato BuscarContrato(int codEmp, int codTipoContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaTipoContrato", ReplyAction="http://tempuri.org/IServicio/AltaTipoContratoResponse")]
        void AltaTipoContrato(Administracion.ServicioWCF.TipoContrato unTipoContrato, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaTipoContrato", ReplyAction="http://tempuri.org/IServicio/BajaTipoContratoResponse")]
        void BajaTipoContrato(Administracion.ServicioWCF.TipoContrato unTipoContrato, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarTipoContrato", ReplyAction="http://tempuri.org/IServicio/ModificarTipoContratoResponse")]
        void ModificarTipoContrato(Administracion.ServicioWCF.TipoContrato unTipoContrato, Administracion.ServicioWCF.Usuario usuLogueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarContratos", ReplyAction="http://tempuri.org/IServicio/ListarContratosResponse")]
        string ListarContratos();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Administracion.ServicioWCF.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Administracion.ServicioWCF.IServicio>, Administracion.ServicioWCF.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaUsuario(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.AltaUsuario(unUsuario, usuLogueado);
        }
        
        public void BajaUsuario(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.BajaUsuario(unUsuario, usuLogueado);
        }
        
        public void ModificarUsuario(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.ModificarUsuario(unUsuario, usuLogueado);
        }
        
        public Administracion.ServicioWCF.Usuario BuscarUsuario(int pCedula) {
            return base.Channel.BuscarUsuario(pCedula);
        }
        
        public void CambioPass(Administracion.ServicioWCF.Usuario unUsuario, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.CambioPass(unUsuario, usuLogueado);
        }
        
        public Administracion.ServicioWCF.Usuario Logueo(string pNomUsu) {
            return base.Channel.Logueo(pNomUsu);
        }
        
        public void AgregaExtras(int pCedula, System.DateTime pFecha, int pMinutos) {
            base.Channel.AgregaExtras(pCedula, pFecha, pMinutos);
        }
        
        public void AltaPago(Administracion.ServicioWCF.Pago unPago, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.AltaPago(unPago, usuLogueado);
        }
        
        public System.DateTime PagoDeUnaFactura(int codContrato, int codEmp, int monto, int codCli, System.DateTime fecha) {
            return base.Channel.PagoDeUnaFactura(codContrato, codEmp, monto, codCli, fecha);
        }
        
        public Administracion.ServicioWCF.Pago[] listar(Administracion.ServicioWCF.Usuario usuLogueado) {
            return base.Channel.listar(usuLogueado);
        }
        
        public Administracion.ServicioWCF.Empresa BuscarEmpresa(int codEmp) {
            return base.Channel.BuscarEmpresa(codEmp);
        }
        
        public void AltaEmpresa(Administracion.ServicioWCF.Empresa unaEmpresa, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.AltaEmpresa(unaEmpresa, usuLogueado);
        }
        
        public void BajaEmpresa(Administracion.ServicioWCF.Empresa unaEmpresa, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.BajaEmpresa(unaEmpresa, usuLogueado);
        }
        
        public void ModificarEmpresa(Administracion.ServicioWCF.Empresa unaEmpresa, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.ModificarEmpresa(unaEmpresa, usuLogueado);
        }
        
        public Administracion.ServicioWCF.Empresa[] ListarEmpresas() {
            return base.Channel.ListarEmpresas();
        }
        
        public Administracion.ServicioWCF.TipoContrato BuscarContrato(int codEmp, int codTipoContrato) {
            return base.Channel.BuscarContrato(codEmp, codTipoContrato);
        }
        
        public void AltaTipoContrato(Administracion.ServicioWCF.TipoContrato unTipoContrato, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.AltaTipoContrato(unTipoContrato, usuLogueado);
        }
        
        public void BajaTipoContrato(Administracion.ServicioWCF.TipoContrato unTipoContrato, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.BajaTipoContrato(unTipoContrato, usuLogueado);
        }
        
        public void ModificarTipoContrato(Administracion.ServicioWCF.TipoContrato unTipoContrato, Administracion.ServicioWCF.Usuario usuLogueado) {
            base.Channel.ModificarTipoContrato(unTipoContrato, usuLogueado);
        }
        
        public string ListarContratos() {
            return base.Channel.ListarContratos();
        }
    }
}
